# Generated by Django 2.0.2 on 2018-06-04 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='title',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='content',
        ),
    ]
